### PR TITLE
Update runtime to 3.34

### PR DESCRIPTION
**Pull request by phako**
Augments #18 with the new runtime

### CODE REVIEW

**Comment by alexlarsson** [comment]
bot, build

**Comment by phako** [comment]
bot, build

**Comment by TingPing** [comment]
Remove and migrate DConf permissions also, like: https://github.com/flathub/org.gnome.Totem/pull/36/commits/ae1b3e6a1002f6b133d44fa79a677ed43d6c7323

**Comment by phako** [comment]
@TingPing Unfortinately the app-id does not match the dconf path for historic reasons... Is there a way to fix that somehow? (/org/yorba/shotwell vs. org.gnome.Shotwell)

**Comment by phako** [comment]
that does not work... 
```
flatpak run org.gnome.Shotwell

(process:2): Gtk-WARNING **: 11:30:21.581: Locale not supported by C library.
	Using the fallback 'C' locale.

** (shotwell:2): ERROR **: 11:30:21.701: PhotoFileFormat.vala:278: Unsupported file format PHOTO_FILE_FORMAT_UNKNOWN

```

**Comment by phako** [comment]
> that does not work...
> 
> ```
> flatpak run org.gnome.Shotwell
> 
> (process:2): Gtk-WARNING **: 11:30:21.581: Locale not supported by C library.
> 	Using the fallback 'C' locale.
> 
> ** (shotwell:2): ERROR **: 11:30:21.701: PhotoFileFormat.vala:278: Unsupported file format PHOTO_FILE_FORMAT_UNKNOWN
> ```

My bad, I was running on a database created by shotwell unstable

**Comment by TingPing** [comment]
> @TingPing Unfortinately the app-id does not match the dconf path for historic reasons... Is there a way to fix that somehow? (/org/yorba/shotwell vs. org.gnome.Shotwell)

Just for historical purposes this was discuss on IRC; The only solution to that is to migrate the settings manually then remove the permission later which phako said they planned on doing.

**Pull request merged**
